before_script:
# with postgres
  #- "cp config/database.yml.travis config/database.yml"
  #- "psql -c 'create database myapp_test;' -U postgres"
# db and init setup
  - "cp config/database.yml.sqlite3 config/database.yml"
  - "mkdir -p tmp/pids log"
# dependencies
  - "gem update --system 1.4.1 > /dev/null 2>&1"
  - "sudo apt-get -y install po4a tango-icon-theme > /dev/null 2>&1"
# translations and db schema
  - "rake noosfero:translations:compile > /dev/null 2>&1"
  - "bundle exec rake db:schema:load > /dev/null 2>&1"
# enable plugins run their migrations
  - "script/noosfero-plugins enableall"
  - "bundle exec rake db:migrate > /dev/null 2>&1"
# for selenium
#  - "sh -e /etc/init.d/xvfb start"

script: ci/travis.rb

rvm:
  - 1.8.7
env: 
  - TASK=test:units
  - TASK=test:functionals
  - TASK=test:integration
  - TASK=cucumber
  #- TASK=selenium
  - TASK=test:noosfero_plugins

notifications:
#  irc: "irc.freenode.org#noosfero"
