before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "psql -c 'create database myapp_test;' -U postgres"
  - "mkdir -p tmp/pids log"
  - "gem update --system 1.4.1"

script: "RAILS_ENV=test bundle exec rake test"

rvm:
  - 1.8.7
env: DB=postgres

notifications:
  irc: "irc.freenode.org#noosfero"
