before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "psql -c 'create database myapp_test;' -U postgres"
  - "mkdir -p tmp/pids log"
  - "gem update --system 1.4.1 > /dev/null 2>&1"
  - "sudo apt-get install po4a tango-icon-theme -y > /dev/null 2>&1"
  - "RAILS_ENV=test rake noosfero:translations:compile > /dev/null 2>&1"
  - "RAILS_ENV=test bundle exec rake db:schema:load > /dev/null 2>&1"
  - "script/noosfero-plugins enableall"
  - "RAILS_ENV=test bundle exec rake db:migrate > /dev/null 2>&1"
  - "sh -e /etc/init.d/xvfb start"

script: "export DISPLAY=:99.0 && bundle exec rake $TEST"

rvm:
  - 1.8.7
env: 
  - DB=postgres
  - TEST=test:units
  - TEST=test:functionals
  - TEST=test:integration
  - TEST=test:plugins
  - TEST=cucumber

notifications:
  irc: "irc.freenode.org#noosfero"
