notifications:
  email:
    - braulio@eita.org.br

language: ruby
rvm:
  - ree

before_install:
# dependencies
  - gem update --system 1.4.1
  - sudo apt-get -y install po4a iso-codes tango-icon-theme openjdk-6-jre curl wget
  - sudo apt-get -y install libmagickwand-dev libpq-dev libreadline-dev libsqlite3-dev libxslt1-dev
# postgres setup
  - psql -c 'create database myapp_test;' -U postgres
# selenium support
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - mkdir -p tmp/pids log
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:schema:load --trace
  #- bundle exec script/noosfero-plugins enableall
  #- bundle exec rake db:migrate --trace

env: 
  - TASK=test:units
  - TASK=test:functionals
  - TASK=test:integration
  - TASK=cucumber
  - TASK=selenium
  - TASK=test:noosfero_plugins

script:
  - bundle exec rake $TASK --trace
